apiVersion: v1
kind: Service
metadata:
  labels:
    app: dotnet-webapi
  name: dotnet-webapi
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5003
  - name: https
    port: 5003
    protocol: TCP
    targetPort: 5003
  - name: http3
    port: 5003
    protocol: UDP
    targetPort: 5003
  selector:
    app: dotnet-webapi
