name: CI

on:
  push:
    branches:
    - 'main'
    tags:
    - 'v*'
    paths:
    - 'src/**'
  pull_request:
    branches:
    - 'main'
    paths:
    - 'src/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NMAE: simpleapi
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      
    - name: Publish
      run: dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=DefaultContainer
      working-directory: ./src/SimpleApi

    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Tag built container
      uses: actions-hub/docker/cli@master
      with:
        args: tag ${{ IMAGE_NAME }}:1.0.0 ${{ env.REGISTRY }}/${{ IMAGE_NAME }}:${{ TAG }}
        
    - name: Push built container
      uses: actions-hub/docker/cli@master
      with:
        args: push ${{ env.REGISTRY }}/${{ IMAGE_NAME }}:${{ TAG }}
